# This file was generated by GoReleaser. DO NOT EDIT.
cask "bifrost" do
  version "0.19.1"

  on_macos do
    on_intel do
      sha256 "0b143d6e1aaaf38632f8b4241d30ae7c52d9b0871397d45b9fdfdc48e7647c7d"
      url "https://github.com/adaouat/bifrost/releases/download/v#{version}/bifrost_#{version}_darwin_amd64"
      binary "bifrost_0.19.1_darwin_amd64", target: "bifrost"
    end
    on_arm do
      sha256 "6a680d27165830cc59cba44e79aa77ebc59002c945aa80ced0def1175c6ccfb5"
      url "https://github.com/adaouat/bifrost/releases/download/v#{version}/bifrost_#{version}_darwin_arm64"
      binary "bifrost_0.19.1_darwin_arm64", target: "bifrost"
    end
  end

  on_linux do
    on_intel do
      sha256 "f0db8a7de0ad2853ddc7be7eff8f91b95f4b687cfbaa63c399aa80784b2f95b9"
      url "https://github.com/adaouat/bifrost/releases/download/v#{version}/bifrost_#{version}_linux_amd64"
      binary "bifrost_0.19.1_linux_amd64", target: "bifrost"
    end
    on_arm do
      sha256 "252de9e62ac51687e9c9e6361401a9bb961f5b24c10d2087e2bcdd4ee86d71f7"
      url "https://github.com/adaouat/bifrost/releases/download/v#{version}/bifrost_#{version}_linux_arm64"
      binary "bifrost_0.19.1_linux_arm64", target: "bifrost"
    end
  end

  name "bifrost"
  desc "Atomic deployment CLI"
  homepage "https://github.com/adaouat/bifrost"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
