# This file was generated by GoReleaser. DO NOT EDIT.
cask "bifrost" do
  version "0.22.0"

  on_macos do
    on_intel do
      sha256 "58825b607f239b1646bbcde004b6bf4038d67ad44529516b283e234f39aa8f7b"
      url "https://github.com/adaouat/bifrost/releases/download/v#{version}/bifrost_#{version}_darwin_amd64"
      binary "bifrost_0.22.0_darwin_amd64", target: "bifrost"
    end
    on_arm do
      sha256 "1963bae5e96718781561fe68a91fe86a37b9e64a6a178f8eeaff1054ac502cbc"
      url "https://github.com/adaouat/bifrost/releases/download/v#{version}/bifrost_#{version}_darwin_arm64"
      binary "bifrost_0.22.0_darwin_arm64", target: "bifrost"
    end
  end

  on_linux do
    on_intel do
      sha256 "5ba82908c99209923c6d68293620d95af5dc2c7065b00d4db1087b682b0425d2"
      url "https://github.com/adaouat/bifrost/releases/download/v#{version}/bifrost_#{version}_linux_amd64"
      binary "bifrost_0.22.0_linux_amd64", target: "bifrost"
    end
    on_arm do
      sha256 "d2dac0b87845c70064ffa0255658a4233d3bc600db77e7b908958bb1da798094"
      url "https://github.com/adaouat/bifrost/releases/download/v#{version}/bifrost_#{version}_linux_arm64"
      binary "bifrost_0.22.0_linux_arm64", target: "bifrost"
    end
  end

  name "bifrost"
  desc "Atomic deployment CLI"
  homepage "https://github.com/adaouat/bifrost"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
