# This file was generated by GoReleaser. DO NOT EDIT.
cask "bifrost" do
  version "0.17.0"

  on_macos do
    on_intel do
      sha256 "be9fc84bf058712bbc690a862b76e4f95425c75ca89c748e5e23e4d245cbe0cc"
      url "https://github.com/adaouat/bifrost/releases/download/v#{version}/bifrost_#{version}_darwin_amd64"
      binary "bifrost_0.17.0_darwin_amd64", target: "bifrost"
    end
    on_arm do
      sha256 "d25a6349d0038827047ae04002d68f6f16234ae370d2c6941514cb5779aa6b1e"
      url "https://github.com/adaouat/bifrost/releases/download/v#{version}/bifrost_#{version}_darwin_arm64"
      binary "bifrost_0.17.0_darwin_arm64", target: "bifrost"
    end
  end

  on_linux do
    on_intel do
      sha256 "a6aaec194f024ba89e14f15c51416dda8e98ac615cf4370e606adb86a276ff76"
      url "https://github.com/adaouat/bifrost/releases/download/v#{version}/bifrost_#{version}_linux_amd64"
      binary "bifrost_0.17.0_linux_amd64", target: "bifrost"
    end
    on_arm do
      sha256 "d05a4b7edde9d3ed4a4b6cbe86aaa2041b0d43aa647b7ea273f2f58e439c4df6"
      url "https://github.com/adaouat/bifrost/releases/download/v#{version}/bifrost_#{version}_linux_arm64"
      binary "bifrost_0.17.0_linux_arm64", target: "bifrost"
    end
  end

  name "bifrost"
  desc "Atomic deployment CLI"
  homepage "https://github.com/adaouat/bifrost"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
