# This file was generated by GoReleaser. DO NOT EDIT.
cask "heraut" do
  version "0.42.0"

  on_macos do
    on_intel do
      sha256 "62dd95af6874d40acadbf8c71d5fa20ad1badf65052e1868933aef3974bb3fca"
      url "https://github.com/adaouat/heraut/releases/download/v#{version}/heraut_#{version}_darwin_amd64"
      binary "heraut_0.42.0_darwin_amd64", target: "heraut"
    end
    on_arm do
      sha256 "6204d8adc537417452e72b3d2b2f2f4e94fcbafbc5fdf5da9b00513208d1c772"
      url "https://github.com/adaouat/heraut/releases/download/v#{version}/heraut_#{version}_darwin_arm64"
      binary "heraut_0.42.0_darwin_arm64", target: "heraut"
    end
  end

  on_linux do
    on_intel do
      sha256 "0eaa6e4948b3714feb8bb5bbdc858cee7047ee317be5988d3088e97e9fc42ffa"
      url "https://github.com/adaouat/heraut/releases/download/v#{version}/heraut_#{version}_linux_amd64"
      binary "heraut_0.42.0_linux_amd64", target: "heraut"
    end
    on_arm do
      sha256 "6292f5ffde94f9db5189f63a923d03dc6b5ad81051bb60ed57868767362e5307"
      url "https://github.com/adaouat/heraut/releases/download/v#{version}/heraut_#{version}_linux_arm64"
      binary "heraut_0.42.0_linux_arm64", target: "heraut"
    end
  end

  name "heraut"
  desc "Release management for git-based projects"
  homepage "https://github.com/adaouat/heraut"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
