# This file was generated by GoReleaser. DO NOT EDIT.
cask "heraut" do
  version "0.69.0"

  on_macos do
    on_arm do
      sha256 "9eb9a28c3cf5fcae9c5dd2e3a1c26a4e4f302268b93c16f86fe63925d1a6cac0"
      url "https://github.com/adaouat/heraut/releases/download/#{version}/heraut_#{version}_darwin_arm64"
      binary "heraut_0.69.0_darwin_arm64", target: "heraut"
    end
    on_intel do
      sha256 "71ab2b5ae6974d56f3a14506d67ece6da67f308ce9bb0abbf44ee22f39620875"
      url "https://github.com/adaouat/heraut/releases/download/#{version}/heraut_#{version}_darwin_amd64"
      binary "heraut_0.69.0_darwin_amd64", target: "heraut"
    end
  end
  on_linux do
    on_arm do
      sha256 "3165f647772ef31f0f710289c436410e75d38fb1f0f7444794c370c5ba66a53e"
      url "https://github.com/adaouat/heraut/releases/download/#{version}/heraut_#{version}_linux_arm64"
      binary "heraut_0.69.0_linux_arm64", target: "heraut"
    end
    on_intel do
      sha256 "ce55d141e4e8287fa23a96763deb47584b927e7b77500e3516bb101031459377"
      url "https://github.com/adaouat/heraut/releases/download/#{version}/heraut_#{version}_linux_amd64"
      binary "heraut_0.69.0_linux_amd64", target: "heraut"
    end
  end

  name "heraut"
  desc "Release management for git-based projects"
  homepage "https://github.com/adaouat/heraut"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required
end
