# This file was generated by GoReleaser. DO NOT EDIT.
cask "heraut" do
  version "0.51.0"

  on_macos do
    on_intel do
      sha256 "09628e8d671d761d39c782fbac7d45ea5bd113ff56c9af392fae0b95bf6d5fd0"
      url "https://github.com/adaouat/heraut/releases/download/v#{version}/heraut_#{version}_darwin_amd64"
      binary "heraut_0.51.0_darwin_amd64", target: "heraut"
    end
    on_arm do
      sha256 "d51fe21e4be909c5a3d075787f6ca21870e26a8a1da2e2dd7228f05d9d22b6d4"
      url "https://github.com/adaouat/heraut/releases/download/v#{version}/heraut_#{version}_darwin_arm64"
      binary "heraut_0.51.0_darwin_arm64", target: "heraut"
    end
  end

  on_linux do
    on_intel do
      sha256 "2fd605eb90db40d501eafe49133e0f38271ef830f33edf991558f7298dd0332d"
      url "https://github.com/adaouat/heraut/releases/download/v#{version}/heraut_#{version}_linux_amd64"
      binary "heraut_0.51.0_linux_amd64", target: "heraut"
    end
    on_arm do
      sha256 "8412e571ac26b552f4beddfab7a4f80152f577026086dba4268de5fd1118750c"
      url "https://github.com/adaouat/heraut/releases/download/v#{version}/heraut_#{version}_linux_arm64"
      binary "heraut_0.51.0_linux_arm64", target: "heraut"
    end
  end

  name "heraut"
  desc "Release management for git-based projects"
  homepage "https://github.com/adaouat/heraut"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
