# This file was generated by GoReleaser. DO NOT EDIT.
cask "hermes" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "278bd80be4b193713438dc3e38f0d5609917ea43129b6d1a62fa1f241eed8046"
      url "https://github.com/adaouat/hermes/releases/download/v#{version}/hermes_#{version}_darwin_amd64"
      binary "hermes_0.1.0_darwin_amd64", target: "hermes"
    end
    on_arm do
      sha256 "1e765bb6fe5185a75ca3399af5e93c376a3ac560039a5e62d7e602d60e849a2e"
      url "https://github.com/adaouat/hermes/releases/download/v#{version}/hermes_#{version}_darwin_arm64"
      binary "hermes_0.1.0_darwin_arm64", target: "hermes"
    end
  end

  name "hermes"
  desc "JetBrains IDE project locator for Alfred, Raycast, and other launchers"
  homepage "https://github.com/adaouat/hermes"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
